### PR TITLE
#10 Fixed

### LINKED ISSUE #10: Баг: ошибки в AuthorizationController и ProfileController
Имя класса ProfileController занято Spring'ом.
В AuthorizationController будет использован UserRequestDto и UserResponseDto вместо LoginDto и UserDto.

### PR DESCRIPTION
**Pull request by Nikitinmn42**
ProfileController renamed to UserProfileController, AuthorizationController - DTOs replaced

### CODE REVIEW

File: src/main/java/com/developing/simbir_product/controller/UserProfileController.java [hunk 1]
```diff
@@ -10,7 +10,7 @@
 @Tag(name = "Управление профилем")
 @RequestMapping(value = "/profile")
 @RestController
-public class ProfileController {
+public class UserProfileController {
     @Operation(summary = "Получить страницу c профилем пользователя")
     @GetMapping(value = "")
```
Comment (hotabsc) [inline src/main/java/com/developing/simbir_product/controller/UserProfileController.java]: можно без (value = "")
